import { ArrowRight, Download, ListFilter, X } from 'lucide-react'
import type { AuditEntry, Scenario } from '../types'
import { clock,pct } from '../state'
export function AuditRows({entries,scenario,onTrack}:{entries:AuditEntry[];scenario:Scenario;onTrack?:(id:string)=>void}){
  if(!entries.length)return <div className="empty-state">No allocation decisions at this time.<br/>The observation window comes first.</div>
  return <div className="audit-rows">{entries.map(a=><article className="audit-entry" key={a.id}><div className="audit-entry-top"><span className="mono">{clock(a.time)}</span><span className={`state state-${a.action.toLowerCase()}`}>{a.action}</span><button className="text-button" onClick={()=>onTrack?.(a.track_id)}>{a.track_id}<ArrowRight size={11}/>{a.resource_id??'WATCH'}</button></div><p>{a.reason}</p><div className="audit-numbers"><span>{scenario.config.destinations.find(d=>d.id===a.leading_destination)?.short_name} {pct(a.probability)}</span><span>EC {a.factors.expected_consequence.toFixed(2)}</span><span>P {a.priority.toFixed(2)}</span><span>C {pct(a.factors.confidence)}</span></div><details><summary>Decision evidence & transaction snapshot</summary><dl className="compact-dl"><dt>Previous leading destination</dt><dd>{a.previous_leading_destination??'—'}</dd><dt>Entropy</dt><dd>{a.factors.uncertainty.toFixed(3)}</dd><dt>Urgency</dt><dd>{a.factors.urgency.toFixed(3)}</dd><dt>Escalation</dt><dd>{a.factors.escalation.toFixed(3)}</dd><dt>Scarcity pressure</dt><dd>{a.factors.scarcity.toFixed(3)}</dd><dt>Release persistence</dt><dd>{a.factors.persistence} cycles</dd><dt>Assignment snapshot</dt><dd className="snapshot">{Object.entries(a.assignments).map(([r,t])=>`${r} → ${t}`).join(' · ')||'No assignments'}</dd></dl></details></article>)}</div>
}
export function AuditDrawer({entries,scenario,onClose,onTrack,time}:{entries:AuditEntry[];scenario:Scenario;onClose:()=>void;onTrack:(id:string)=>void;time:number}){
  function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({time,entries},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`swarmshield-audit-${time}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <section className="audit-drawer" aria-label="Decision audit log"><div className="panel-heading"><div><ListFilter size={16}/><h2>Decision audit</h2><span className="count">{entries.length}</span></div><div><button className="icon-button" aria-label="Export audit JSON" onClick={download}><Download size={16}/></button><button className="icon-button" aria-label="Close audit" onClick={onClose}><X size={17}/></button></div></div><p className="drawer-intro">Evidence recorded at each decision. Showing transactions through {clock(time)}; multiple transactions at one timestamp are ordered by record ID.</p><AuditRows entries={[...entries].reverse()} scenario={scenario} onTrack={onTrack}/></section>
}
