import { ArrowDownRight, ChartNoAxesCombined, X } from 'lucide-react'
import type { Frame, Run } from '../types'
import { pct } from '../state'
export function ExposureChart({run,time}:{run:Run;time:number}){
  const frames=run.frames.slice(0,Math.floor(time)+1)
  const max=Math.max(1,...frames.map(f=>Math.max(f.metrics.swarm.cumulative_exposure,f.metrics.baseline.cumulative_exposure)))
  const path=(key:'swarm'|'baseline')=>frames.map((f,i)=>`${i?'L':'M'} ${f.time/run.duration*500} ${110-f.metrics[key].cumulative_exposure/max*100}`).join(' ')
  return <svg className="exposure-chart" viewBox="0 0 510 135" role="img" aria-label="Cumulative uncovered expected consequence over simulation time"><line x1="0" y1="110" x2="500" y2="110" stroke="#293343"/><line x1="0" y1="55" x2="500" y2="55" stroke="#202c39" strokeDasharray="3 5"/><path d={path('baseline')} fill="none" stroke="#8190a9" strokeWidth="2" strokeDasharray="5 4"/><path d={path('swarm')} fill="none" stroke="#6ae3c3" strokeWidth="2.5"/><text x="0" y="130">0s</text><text x="475" y="130">{run.duration}s</text><text x="0" y="10">{max.toFixed(0)} consequence·seconds</text></svg>
}
export function ComparisonPanel({frame,run,onClose}:{frame:Frame;run:Run;onClose:()=>void}){
  const {swarm,baseline}=frame.metrics
  const improvement=baseline.cumulative_exposure?1-swarm.cumulative_exposure/baseline.cumulative_exposure:0
  const rows=[['Critical tracks covered',`${swarm.critical_tracks_covered} / ${swarm.critical_tracks}`,`${baseline.critical_tracks_covered} / ${baseline.critical_tracks}`],['Uncovered expected consequence',swarm.exposure.toFixed(2),baseline.exposure.toFixed(2)],['Low-consequence commitments',swarm.low_consequence_commitments,baseline.low_consequence_commitments],['Reallocations',swarm.reassignments,baseline.reassignments],['Resource utilization',pct(swarm.utilization),pct(baseline.utilization)],['Assignment stability',pct(swarm.stability),pct(baseline.stability)],['Critical asset classes covered',swarm.critical_assets_covered,baseline.critical_assets_covered]]
  return <section className="comparison-panel" aria-label="Baseline comparison"><div className="panel-heading"><div><ChartNoAxesCombined size={16}/><h2>Policy comparison</h2></div><button className="icon-button" onClick={onClose} aria-label="Close comparison"><X size={17}/></button></div><div className="comparison-body"><span className="eyebrow">SAME OBSERVATIONS. DIFFERENT DECISIONS.</span><h2>Make scarcity count.</h2><div className="comparison-hero"><ArrowDownRight size={28}/><strong>{(improvement*100).toFixed(1)}<small>%</small></strong><span>less cumulative<br/>uncovered consequence</span></div><p className="muted">Relative to first-come, first-served allocation, through the current frame.</p><ExposureChart run={run} time={frame.time}/><div className="chart-key"><span><i className="mint"/>SwarmShield</span><span><i className="slate"/>First come, first served</span></div><table><thead><tr><th>Metric</th><th>SwarmShield</th><th>Baseline</th></tr></thead><tbody>{rows.map(([label,s,b])=><tr key={label}><td>{label}</td><td>{s}</td><td>{b}</td></tr>)}</tbody></table><p className="comparison-note">The baseline commits in detection order, using track ID for simultaneous arrivals, and retains its assignments. Metrics use the same inferred consequence for both policies, not hidden destinations. Stability = 1 − reallocations / (current assignments + reallocations). This authored scenario illustrates tradeoffs; it is not a general performance benchmark.</p></div></section>
}
