import { useState } from 'react'
import { ArrowUpRight, ChevronRight, Crosshair, MapPin, Radio, ShieldCheck } from 'lucide-react'
import type { AuditEntry, Frame, Scenario, Selection, Track } from '../types'
import { clock,leading,pct,trackColor } from '../state'
import { AuditRows } from './Audit'

export function ProbabilityBars({track,scenario}:{track:Track;scenario:Scenario}){
  const top=leading(track)
  return <div className="probability-bars" aria-label="Destination probability distribution">{scenario.config.destinations.map(d=><div key={d.id} className={`probability-row ${d.id===top?'leading':''}`}><div><span><small>{d.id}</small>{d.short_name}</span><b>{(track.probabilities[d.id]*100).toFixed(1)}<small>%</small></b></div><div className="probability-track"><i style={{width:`${track.probabilities[d.id]*100}%`}}/></div></div>)}<div className="distribution-total"><span>Complete distribution</span><span>Σ {(Object.values(track.probabilities).reduce((a,b)=>a+b,0)*100).toFixed(1)}%</span></div></div>
}
function Gauge({label,value,color}:{label:string;value:number;color?:string}){return <div className="gauge"><div><span>{label}</span><b style={{color}}>{pct(value)}</b></div><div><i style={{width:`${value*100}%`,background:color}}/></div></div>}
export function Inspector({selection,frame,scenario,audit,onSelect}:{selection:Selection;frame:Frame;scenario:Scenario;audit:AuditEntry[];onSelect:(s:Selection)=>void}){
  const [tab,setTab]=useState<'overview'|'evidence'|'history'>('overview')
  const track=selection.kind==='track'?frame.tracks.find(t=>t.id===selection.id):undefined
  const resource=selection.kind==='resource'?frame.resources.find(r=>r.id===selection.id):undefined
  const destination=selection.kind==='destination'?scenario.config.destinations.find(d=>d.id===selection.id):undefined
  const site=selection.kind==='site'?scenario.config.sites.find(s=>s.id===selection.id):undefined
  const trackAudit=track?audit.filter(a=>a.track_id===track.id).reverse():[]
  return <aside className="inspector panel" aria-label="Context inspector"><div className="panel-heading"><div><Crosshair size={15}/><h2>Context inspector</h2></div><span className="live-pill">LIVE FRAME</span></div><div className="inspector-content">
    {track&&<><div className="inspector-title"><div className="object-icon" style={{color:trackColor(track)}}><Crosshair size={23}/></div><div><span className="eyebrow">INCOMING TRACK</span><h2>{track.id}<span className={`state state-${track.state.toLowerCase()}`}>{track.state}</span></h2></div></div><div className="inspector-tabs">{(['overview','evidence','history'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='history'&&<span>{trackAudit.length}</span>}</button>)}</div>
    {tab==='overview'&&<><div className="risk-summary"><div><span className="eyebrow">ALLOCATION PRIORITY</span><strong style={{color:trackColor(track)}}>{(track.priority*100).toFixed(0)}<small>/ 100</small></strong></div><svg viewBox="0 0 60 60" className="priority-ring"><circle cx="30" cy="30" r="24"/><circle cx="30" cy="30" r="24" stroke={trackColor(track)} strokeDasharray={`${track.priority*151} 151`} transform="rotate(-90 30 30)"/><text x="30" y="34">{track.assigned_resource?'01':'00'}</text></svg></div><div className="assignment-card"><ShieldCheck size={16}/><div><small>Assigned capacity</small><button className="text-button" onClick={()=>track.assigned_resource&&onSelect({kind:'resource',id:track.assigned_resource})}>{track.assigned_resource??'Monitoring only'}{track.assigned_resource&&<ArrowUpRight size={14}/>}</button></div><span className="tiny-dot" style={{background:track.assigned_resource?'var(--mint)':'var(--muted)'}}/></div><div className="gauge-pair"><Gauge label="Confidence" value={track.confidence} color="var(--mint)"/><Gauge label="Uncertainty" value={track.entropy} color="#aca5d8"/></div><div className="section-title"><h3>Destination inference</h3><span>8 CLASSES</span></div><ProbabilityBars track={track} scenario={scenario}/><div className="reason-card"><span className="eyebrow">WHY THIS DECISION</span><p>{track.reason}</p></div><div className="inspector-note">Estimates come from noisy observations. Open water indicates lower current consequence, never a safety guarantee.</div></>}
    {tab==='evidence'&&<><div className="section-title"><h3>Transparent priority</h3><span>0–1 MODEL</span></div><dl className="factor-grid"><dt>Expected consequence</dt><dd>{track.expected_consequence.toFixed(3)}</dd><dt>Confidence</dt><dd>{track.confidence.toFixed(3)}</dd><dt>Uncertainty / entropy</dt><dd>{track.entropy.toFixed(3)}</dd><dt>Urgency</dt><dd>{track.urgency.toFixed(3)}</dd><dt>Escalation</dt><dd>{track.escalation.toFixed(3)}</dd><dt>Scarcity pressure</dt><dd>{track.factors.scarcity.toFixed(3)}</dd><dt>Unassigned penalty</dt><dd>−{track.factors.reassignment_penalty.toFixed(3)}</dd><dt className="factor-total">Priority score</dt><dd className="factor-total">{track.priority.toFixed(3)}</dd></dl><div className="formula">{track.factors.consequence_term.toFixed(3)} consequence<br/>+ {track.factors.uncertainty_term.toFixed(3)} uncertainty watch<br/>+ {track.factors.escalation_term.toFixed(3)} escalation<br/>+ {track.factors.scarcity_term.toFixed(3)} scarcity<br/>− {track.factors.reassignment_penalty.toFixed(3)} unassigned penalty</div><div className="section-title"><h3>Release evidence</h3><span>{track.low_consequence_cycles}/{scenario.config.hysteresis.release_persistence_cycles} CYCLES</span></div><div className="release-gates">{[
      [`Open water ≥ ${pct(scenario.config.hysteresis.water_probability)}`,track.probabilities.A08>=scenario.config.hysteresis.water_probability],
      [`Consequence ≤ ${scenario.config.hysteresis.release_consequence}`,track.expected_consequence<=scenario.config.hysteresis.release_consequence],
      [`Confidence ≥ ${pct(scenario.config.hysteresis.release_confidence)}`,track.confidence>=scenario.config.hysteresis.release_confidence],
      [`No major turn for ${scenario.config.hysteresis.turn_quiet_period}s`,frame.time-track.last_major_turn>=scenario.config.hysteresis.turn_quiet_period],
    ].map(([label,passed])=><div key={String(label)}><span className={`tiny-dot ${passed?'mint':'slate'}`}/>{label}<b>{passed?'MET':'WAIT'}</b></div>)}</div><div className="section-title"><h3>Observed motion</h3><span>SCENE UNITS</span></div><dl className="compact-dl"><dt>Position x / z</dt><dd>{track.position[0].toFixed(1)} / {track.position[2].toFixed(1)}</dd><dt>Altitude</dt><dd>{track.altitude.toFixed(1)}</dd><dt>Observed speed</dt><dd>{Math.hypot(...track.velocity).toFixed(3)}</dd><dt>Heading</dt><dd>{(track.heading*180/Math.PI).toFixed(1)}°</dd><dt>Track stability</dt><dd>{pct(track.stability)}</dd><dt>Heading variance</dt><dd>{track.heading_variance.toFixed(4)}</dd></dl><div className="section-title"><h3>Recent observations</h3></div><table className="observation-table"><thead><tr><th>Time</th><th>X</th><th>Z</th><th>Heading</th></tr></thead><tbody>{track.observations.slice(-6).reverse().map(o=><tr key={o.time}><td>{clock(o.time)}</td><td>{o.position[0].toFixed(1)}</td><td>{o.position[2].toFixed(1)}</td><td>{(o.heading*180/Math.PI).toFixed(0)}°</td></tr>)}</tbody></table></>}
    {tab==='history'&&<><div className="section-title"><h3>Observed changes</h3></div>{track.event_history.length?track.event_history.slice(-5).reverse().map(e=><p className="event-history" key={e}>{e}</p>):<p className="muted">No significant heading changes observed.</p>}<div className="section-title"><h3>Decision history</h3></div><AuditRows entries={trackAudit} scenario={scenario}/></>}
    </>}
    {resource&&<><div className="inspector-title"><div className="object-icon resource-icon"><ShieldCheck size={24}/></div><div><span className="eyebrow">SIMULATED RESOURCE</span><h2>{resource.id}</h2></div><span className="state">{resource.state}</span></div><div className="reason-card"><span className="eyebrow">CURRENT DECISION</span><p>{resource.reason}</p></div><dl className="factor-grid"><dt>Staging site</dt><dd><button className="text-button" onClick={()=>onSelect({kind:'site',id:resource.site_id})}>{resource.site_id}<ChevronRight size={12}/></button></dd><dt>Current assignment</dt><dd>{resource.assigned_track?<button className="text-button" onClick={()=>onSelect({kind:'track',id:resource.assigned_track!})}>{resource.assigned_track}<ChevronRight size={12}/></button>:'Available'}</dd><dt>Assignment since</dt><dd>{resource.assignment_start===null?'—':clock(resource.assignment_start)}</dd><dt>Position x / y / z</dt><dd>{resource.position.map(n=>n.toFixed(1)).join(' / ')}</dd><dt>Visual destination</dt><dd>{resource.visual_destination.map(n=>n.toFixed(1)).join(' / ')}</dd></dl><div className="section-title"><h3>Assignment history</h3></div>{resource.assignment_history.length?resource.assignment_history.slice().reverse().map((r,i)=><div className="resource-history" key={`${r.time}-${i}`}><span className="mono">{clock(r.time)}</span><span className="state">{r.action}</span><button className="text-button" onClick={()=>onSelect({kind:'track',id:r.track_id})}>{r.track_id}<ChevronRight size={12}/></button><p>{r.reason}</p></div>):<div className="empty-state">Staged and available.<br/>Initial observation window in progress.</div>}<div className="inspector-note">Cinematic C2-continuous paths follow a general observation region. Movement has no modeled engagement outcome.</div></>}
    {destination&&<><div className="inspector-title"><div className="object-icon"><MapPin size={24}/></div><div><span className="eyebrow">{destination.id} · DESTINATION</span><h2 className="destination-title">{destination.name}</h2></div></div><dl className="factor-grid"><dt>Category</dt><dd>{destination.category}</dd><dt>Consequence weight</dt><dd>{destination.weight.toFixed(2)}</dd><dt>Probability-weighted count</dt><dd>{frame.tracks.reduce((s,t)=>s+t.probabilities[destination.id],0).toFixed(2)}</dd><dt>Aggregate expected consequence</dt><dd>{frame.tracks.reduce((s,t)=>s+t.probabilities[destination.id]*destination.weight,0).toFixed(2)}</dd><dt>Footprint radius</dt><dd>{destination.radius} scene units</dd></dl><div className="section-title"><h3>Relevant tracks</h3><span>P &gt; 5%</span></div>{frame.tracks.filter(t=>t.probabilities[destination.id]>.05).sort((a,b)=>b.probabilities[destination.id]-a.probabilities[destination.id]).map(t=><button className="destination-track" key={t.id} onClick={()=>onSelect({kind:'track',id:t.id})}><span>{t.id}</span><div><i style={{width:`${t.probabilities[destination.id]*100}%`}}/></div><span>{pct(t.probabilities[destination.id])}</span><ChevronRight size={12}/></button>)}{destination.id==='A08'&&<div className="reason-card"><span className="eyebrow">LOW CONSEQUENCE ≠ SAFE</span><p>Tracks remain under observation. Any heading change can reopen uncertainty and raise priority.</p></div>}</>}
    {site&&<><div className="inspector-title"><div className="object-icon"><Radio size={24}/></div><div><span className="eyebrow">{site.id} · STAGING SITE</span><h2>{site.name}</h2></div></div><p className="muted">Fictional staging location in abstract scene coordinates.</p><dl className="factor-grid"><dt>Position x / z</dt><dd>{site.position[0]} / {site.position[2]}</dd><dt>Stationed resources</dt><dd>{frame.resources.filter(r=>r.site_id===site.id).length}</dd><dt>Currently at site</dt><dd>{frame.resources.filter(r=>r.site_id===site.id&&r.state==='STAGED').length}</dd></dl>{frame.resources.filter(r=>r.site_id===site.id).map(r=><button className="site-resource" key={r.id} onClick={()=>onSelect({kind:'resource',id:r.id})}><ShieldCheck size={17}/><b>{r.id}</b><span>{r.assigned_track?`→ ${r.assigned_track}`:r.state}</span><ChevronRight size={14}/></button>)}</>}
  </div><div className="inspector-footer"><span className="tiny-dot mint"/>Snapshot {clock(frame.time)}<span>OBSERVATION-DRIVEN</span></div></aside>
}
